class StringUtil {
  static const String errorConnection = "Lỗi kết nối!";
  static const String errorLogin = "Đăng Nhập Thất Bại";
  static const String errorGetProfile = "Lấy Thông Tin Thất Bại";
  static const String errorGetQuestion= "Lấy danh sách câu hỏi thất bại";
  static const String errorGetStaffId= "Lấy id nhân viên thất bại";
  static const String errorSubmitSurvey= "Gửi khảo sát thất bại";
  static const String errorGetReceipt= "Tìm dữ liệu thất bại";
  static const String errorCheckPhone = "Kiểm tra số điện thoại thất bại";
  static const String errorAddNewCustomer = "Thêm mới khách hàng thất bại";
  static const String errorGetConsultants = "Lấy danh sách tư vấn thất bại";
  static const String errorGetConsultantDetail = "Lấy chi tiết tư vấn thất bại";
  static const String errorGetServices = "Lấy danh sách dịch vụ thất bại";
  static const String errorAddItem = "Thêm tư vấn thất bại";
  static const String errorBooking = "Đặt lịch thất bại";
  static const String errorGetBookings = "Lây danh sách đặt lịch thất bại";
  static const String errorGetServiceGroup = "Lấy danh sách dịch vụ theo nhóm thất bại";
  static const String errorCreateConsulant= "Tạo tư vấn viên thất bại";
  static const String errorSearchBooking = "Tìm danh sách booking thất bại";
  static const String errorGetListReceipt = "Lấy danh sách receipt thất bại";
  static const String errorRegisterNotify = "Đăng ký notification thất bại";
  static const String errorGetListNotify = "Lấy danh sách notify thất bại";
  static const String errorGetDetailNotify = "Lấy notify thất bại";
  static const String errorGetStaff = "Không tìm thấy nhân viên";
  static const String errorGetListShop = "Lấy danh sách cửa hàng thất bại";
  static const String errorGetReceiptList = "Lấy danh sách biên nhận thất bại";
  static const String errorSendDetailNotify = "Gửi phản hồi thất bại";
  static const String errorGetListLocation = "Lấy danh sách location thất bại";
}