name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_transition: ^1.1.5
  flutter_spinkit: "^3.1.0"
  flutter_datetime_picker: "1.4.0"
  rxdart: ^0.22.6
  http: ^0.12.0+1
  provider: ^3.1.0+1
  camera: ^0.5.8+2
  connectivity: ^0.4.9
  scroll_to_index: any
  flutter_launcher_icons: ^0.7.5
  intl: ^0.15.8
  shared_preferences: "^0.4.2"
  keyboard_actions: ^3.2.1
  path_provider: ^1.6.11
  badges: ^1.1.1
  fluttertoast: ^3.1.3
  exif: ^1.0.3
  flutter_money_formatter: ^0.8.3
  flutter_screenutil: ^2.1.0
  flutter_inner_drawer: ^0.5.4
  firebase_ml_vision: ^0.9.4
  unicorndial: ^1.1.5
  string_validator: ^0.1.4
  autocomplete_textfield: ^1.7.3
  flutter_typeahead: ^1.8.8
  flutter_barcode_scanner: ^1.0.1
  flutter_local_notifications: ^1.4.4+4
  firebase_messaging: ^7.0.0
  pull_to_refresh: ^1.6.2
  expandable: ^4.1.4
  flutter_pagewise: ^1.2.3
  material_segmented_control: ^2.1.0+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:  
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family:  JobwayIcon
      fonts:
       - asset: assets/fonts/JobwayIcon.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.otf
    - family: HelveticaNeue-Bold
      fonts:
        - asset: assets/fonts/HelveticaNeue-Bold.otf
    - family: HelveticaNeue-Medium
      fonts:
        - asset: assets/fonts/HelveticaNeue-Medium.otf
    - family: HelveticaNeue-Light
      fonts:
        - asset: assets/fonts/HelveticaNeue-Light.otf
    - family: HelveticaNeue-UltraLightItalic
      fonts:
        - asset: assets/fonts/HelveticaNeue-UltraLightItalic.otf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Italic
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf
    - family: Roboto-Light
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf  
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
